---
# tasks file for image_builder
# Variable configuration.
- include_tasks: variables.yml

# Setup/install tasks.
- include_tasks: setup-RedHat.yml
  when: ansible_os_family == 'RedHat'

- name: Ensure Cockpit Web Console is started/enabled when GUI is chosen.
  service:
    name: "{{ ib_daemon }}"
    state: started
    enabled: yes
  when: ib_with_gui == true

- name: Ensure Image Builder service "{{ ib_daemon }}" is started and enabled on boot.
  service:
    name: "{{ ib_daemon }}"
    state: started
    enabled: yes
